syncSource:
  replicaSet:
    hostAndPort: ["mongo-primary:27017", "mongo-secondary1:27017", "mongo-secondary2:27017"]

    username: "mongot-user"
    passwordFile: "/etc/mongo/passwordFile"
    tls: false

storage:
  dataPath: "/var/lib/mongot"  # Replace with the path where you want mongot to store search data.
server:
  grpc:
    address: "0.0.0.0:27028"  # Replace with the address and port for mongot listen server
    tls:
      mode: "disabled"

metrics:
  enabled: true
  address: "0.0.0.0:9946"

healthCheck:
  address: "0.0.0.0:8080"

logging:
  verbosity: INFO